/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#594047',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#8d6f77',
        'outline-variant': '#e1bec6',
        'surface-tint': '#ba0060',
        primary: '#db2777',
        'on-primary': '#ffffff',
        'primary-container': '#db2777',
        'on-primary-container': '#fffdff',
        'inverse-primary': '#ffb1c7',
        secondary: '#7c3aed',
        'on-secondary': '#ffffff',
        'secondary-container': '#8a4cfc',
        'on-secondary-container': '#fffbff',
        tertiary: '#835200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#f59e0b',
        'on-tertiary-container': '#fffdff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9e2',
        'primary-fixed-dim': '#ffb1c7',
        'on-primary-fixed': '#3f001c',
        'on-primary-fixed-variant': '#8e0048',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'on-secondary-fixed': '#25005a',
        'on-secondary-fixed-variant': '#5a00c6',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
        'surface-rose': '#fffbfd',
        'surface-rose-muted': '#fdf2f6',
        'surface-glass': 'rgba(255, 255, 255, 0.78)',
        'surface-glass-dark': 'rgba(15, 23, 42, 0.75)',
        'berry-deep': '#9d174d',
        'berry-glow': '#f472b6',
        'berry-tint': '#fdf2f8',
        'slate-surface': '#1e293b',
        'slate-muted': '#64748b',
        'border-rose': '#fce7f3',
        'border-neutral': '#f1f5f9',
        'gold-badge': '#d97706',
        'gold-badge-bg': '#fffbeb',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-xs': ['11px', { lineHeight: '14px', fontWeight: '700', letterSpacing: '0.04em' }],
        'metric-display': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-tablet': '1.25rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.75rem',
      },
      boxShadow: {
        card: '0 4px 20px -2px rgba(219, 39, 119, 0.05), 0 2px 6px -1px rgba(15, 23, 42, 0.03)',
        floating: '0 12px 28px -4px rgba(219, 39, 119, 0.12), 0 4px 10px -2px rgba(15, 23, 42, 0.04)',
        dock: '0 -8px 24px rgba(15, 23, 42, 0.06)',
      },
    },
  },
  plugins: [],
}
